ministryofjustice/opg-data-lpa-uid

.github/workflows/build.yml
delegator/main.go
docker-compose.yml
docs/openapi/openapi.yaml

- Use `PROVIDER_OVERRIDE_LAMBDA=legacy` so we can continue using `LAMBDA_FORWARD_URL`
- Fix the path regex since the function name now contains the region too
- Unrelated, but add an example to the createCase:201 response to easily build mock servers
Add `make test` to pipeline for a bit of loose verification
#patch

Fix Lambda routing

---

Makefile
lambda/create-case/main.go
lambda/create-case/main_test.go

UID is now generated inside a loop, checking the DB for it and regenerating if it is not unique. We break out of the loop if the UID is unique, and store it alongside the other data
VEGA-1792

VEGA-1792 check uid is unique before storing

---

.github/workflows/build.yml
.github/workflows/deploy.yml
Makefile
docker-compose.yml
terraform/aws/.envrc
terraform/aws/.terraform.lock.hcl
terraform/aws/global.tf
terraform/aws/regions.tf
terraform/aws/terraform.tfvars.json
terraform/aws/terrraform.tf
terraform/aws/variables.tf
terraform/modules/region/lambda.tf
terraform/modules/region/variables.tf

- Build and cache images
- Separate unit and integration tests
- Push image to ECR
- Deploy to development
For deployment I've used a pattern from opg-modernising-lpa which uses reusable workflows. I've also fleshed out the AWS workspace folder to create the region resources.
Fixes VEGA-1739 #minor

Add deployment pipeline

---

.github/workflows/build.yml

In order to reference `needs.push.outputs.tag`, the job must depend on the push job.
For VEGA-1739 #patch

Ensure deploy stages have inputs

---

.github/workflows/build.yml
.github/workflows/deploy.yml

Because we deploy to three environments, it overwrites itself and isn't very helpful.
For VEGA-1739 #patch

Stop outputting plan in GitHub comment

---

terraform/modules/region/cloudwatch.tf

We only want to query information about the LPA UID Gateway, not all gateways (lpa-codes, lpa) on the account
Fixes VEGA-1844 #patch

Scope alarms to API Gateway

---

.github/workflows/pact-provider-verification.yml
docker-compose.yml
terraform/modules/region/api_gateway.tf

Verify pacts:
- When making a PR, to ensure the contract hasn't been broken
- When pushing to main, to ensure the contract hasn't been broken and to notify pending Pacts
- When we receive a repository dispatch event of the type "provider-verification", to verify a specific Pact
Fixes VEGA-1753 #patch

Add Pact Provider verification

---

.github/workflows/pact-provider-verification.yml

Tags are awkward to correctly calculate and don't provide us any additional value to commit/branch.
Remove them to simplify the configuration: we can always bring them back if we have a direct need for them in the future
#patch

Stop setting provider tags in Pact

---

docs/openapi/openapi.yaml

The previous PR just made a policy, it didn't enable it.
Fixes VEGA-1855 #minor

Actually switch on IAM auth

---

terraform/modules/region/api_gateway.tf

include wildcards for all methods and stages
Resource format of permissions shown here 
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-control-access-using-iam-policies-to-invoke-api.html#api-gateway-calling-api-permissions
but format of execute-api defined here
https://docs.aws.amazon.com/apigateway/latest/developerguide/arn-format-reference.html
implies stage, http-method and resource-path need to be wilcarded too, else you get a forbidden error when calling.

MLPAB-985 - define the resources that can be accessed 

---

terraform/aws/.terraform.lock.hcl
terraform/modules/region/api_gateway.tf

The templatefile provider has been archived and we are advised to use the templatefile function instead.
This unblocks being able to run a `terraform init` on darwin_arm64 architecture, which failed because there is no compatible package for that platform.
```
|
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this
│ provider may have different platforms supported.
|
```
https://registry.terraform.io/providers/hashicorp/template/latest
https://developer.hashicorp.com/terraform/language/functions/templatefile
This PR should result …

MLPAB-985 - replace templatefile provider with templatefile function

---

terraform/modules/region/lambda.tf

Looks like we need to add the inverse perms for lambda to be triggered by API gateway (see https://repost.aws/knowledge-center/api-gateway-lambda-stage-variable-500)

MLPAB-880: Add lambda permissions

---

terraform/modules/region/api_gateway.tf

- add stage name to custom domain mapping
The stage name from the api gateway deployment resource wasn't returning a value, so "current" wasn't being included in the custom domain mapping.
Adding it to the endpoint of any call would also solve this issue
for example
```shell
aws-vault exec <profile> -- go run uid-tester -baseUrl="https://lpa-uid.api.opg.service.justice.gov.uk/current"
```
This setup would allow for consumers of the API to choose what version (stage) they want to use if the api introduces breaking changes, but as including the stage name appears to be the intended setup, it is now taken from from the stage resource instead.
https://docs.aws.amazon.com/apigateway/latest/developerguide/rest-api-mappings.html

MLPAB-1036 - Fix DNS

---

terraform/modules/region/api_gateway.tf

Path to live fails to delete a stage because it's being used by base path mapping
- redeployments now create new base path mappings instead of updating in place
- base path mappings are created before they are destroyed
This deposes existing resources and destroys them afterwards
```shell
module.eu-west-1.aws_api_gateway_stage.current: Creating...
module.eu-west-1.aws_api_gateway_stage.current: Creation complete after 1s
module.eu-west-1.aws_api_gateway_base_path_mapping.mapping: Creating...
module.eu-west-1.aws_api_gateway_base_path_mapping.mapping: Creation complete after 0s 
module.eu-west-1.aws_api_gateway_base_path_mapping.mapping (deposed object ce384f3a): Destroying... 
module.eu-west-1.aws_api_gateway_base_path_mapping.mapping: Destruction complete after 1s …
```

MLPAB-1140 - BadRequestException: Deleting stage current failed

---

terraform/modules/region/api_gateway.tf
terraform/modules/region/terraform.tf

Changes to permissions or the body of the API were taking 2 deployments to come into play.
It seems that creating a new API on those changes using `replace_triggered_by` was causing an issue.
Removing this, and updating the triggers for deployments, we now only require one. New API paths are available immediately and permission changes take about 10 seconds to propagate.
Also, this seems to remove the need to recreate methods and stages as implemented previously.
- simplified resource in API policy (as it's attached and only applies to a single api) to decouple the policy from the rest API.
- removed `replace_triggered_by` and the associated null resource
- make sure API and policy are ready before deploying

MLPAB-1146 - Fix deployments

---

terraform/aws/.terraform.lock.hcl

Needed to unblock pipeline since the development state contains v5 definitions.
#patch

Upgrade AWS provider to v5

---

terraform/aws/regions.tf
terraform/aws/terrraform.tf
terraform/local/.terraform.lock.hcl
terraform/local/regions.tf
terraform/modules/region/dynamodb.tf
terraform/modules/region/lpa_applications.tf
terraform/modules/region/variables.tf

When a record is changed in the DynamoDB table, it streams to an AWS Pipe. The Pipe filters to only insert events (so updates and deletes are ignored), and transforms the data from the stream into the following structure:
```json
{
"uid": "M-123456789012",
"source": "APPLICANT",
"type": "hw",
"donor": {
"name": "Jack Rubik",
"dob": "1938-03-18",
"postcode": "W8A0IK"
}
}
```
It also sets the source and detail-type to match [our definition](https://opgtransform.atlassian.net/wiki/spaces/POAS/pages/3647143937/POAS+Events).

VEGA-1939 - Notify Sirius when new records created

---

.github/workflows/build.yml

This ensures that the last 10 `main` builds are kept, in line with the ECR policy for integration repositories.
Fixes VEGA-2012 #patch

Tag main-build ECR image with `main`

---

terraform/aws/terraform.tfvars.json

Fix missing permission that was preventing the MRLPA service's events handling lambda from calling the UID service.
The MRLPA ECS app task still requires permissions for a dependency healthcheck

MLPAB-1655 allow MRLPA events received lambda role to call uid service

---

Makefile
docs/openapi/openapi.yaml
lambda/create-case/main.go
lambda/create-case/main_test.go
lambda/create-case/validation.go
scripts/uid_tester/uid-tester.go
terraform/modules/region/cloudwatch.tf

These are no longer sent by clients requesting UIDs for digital LPAs, so can be removed from the API.

VEGA-2259 Remove support for digital LPAs with hw or pfa subtypes #major

---

terraform/modules/region/cloudwatch.tf

It needs to match the full lambda name

Fix log group name

---

terraform/modules/opg_metrics/main.tf

Previous merge caused a collision with existing resources
Fixes MLPAB-3099
- add env name to api destination resources

MLPAB-3099 - uniquely name api desintations
